// Generated from http://www.dotnetwise.com/Code/Externs/index.html

var BABYLON = {
  Debug: {
    AxesViewer: function () {},
    BoneAxesViewer: function () {},
    PhysicsViewer: function () {},
    SkeletonViewer: function () {},
  },
  AbstractScene: function () {},
  KeepAssets: function () {},
  InstantiatedEntries: function () {},
  AssetContainer: function () {},
  Node: function () {},
  Scene: function () {},
  SceneComponentConstants: function () {},
  Stage: function () {},
  AbstractActionManager: function () {},
  Action: function () {},
  ActionEvent: function () {},
  ActionManager: function () {},
  Condition: function () {},
  ValueCondition: function () {},
  PredicateCondition: function () {},
  StateCondition: function () {},
  SwitchBooleanAction: function () {},
  SetStateAction: function () {},
  SetValueAction: function () {},
  IncrementValueAction: function () {},
  PlayAnimationAction: function () {},
  StopAnimationAction: function () {},
  DoNothingAction: function () {},
  CombineAction: function () {},
  ExecuteCodeAction: function () {},
  SetParentAction: function () {},
  PlaySoundAction: function () {},
  StopSoundAction: function () {},
  InterpolateValueAction: function () {},
  Animatable: function () {},
  _IAnimationState: function () {},
  Animation: function () {},
  TargetedAnimation: function () {},
  AnimationGroup: function () {},
  AnimationPropertiesOverride: function () {},
  EasingFunction: function () {},
  CircleEase: function () {},
  BackEase: function () {},
  BounceEase: function () {},
  CubicEase: function () {},
  ElasticEase: function () {},
  ExponentialEase: function () {},
  PowerEase: function () {},
  QuadraticEase: function () {},
  QuarticEase: function () {},
  QuinticEase: function () {},
  SineEase: function () {},
  BezierCurveEase: function () {},
  RuntimeAnimation: function () {},
  AnimationEvent: function () {},
  AnimationKeyInterpolation: {
    "1": {},
    STEP: {},
  },
  AnimationRange: function () {},
  Analyser: function () {},
  AudioEngine: function () {},
  AudioSceneComponent: function () {},
  Sound: function () {},
  SoundTrack: function () {},
  WeightedSound: function () {},
  Bone: function () {},
  BoneIKController: function () {},
  BoneLookController: function () {},
  Skeleton: function () {},
  CameraInputTypes: {
    ArcRotateCameraGamepadInput: function () {},
    ArcRotateCameraKeyboardMoveInput: function () {},
    ArcRotateCameraMouseWheelInput: function () {},
    ArcRotateCameraPointersInput: function () {},
    ArcRotateCameraVRDeviceOrientationInput: function () {},
    FlyCameraKeyboardInput: function () {},
    FlyCameraMouseInput: function () {},
    FollowCameraKeyboardMoveInput: function () {},
    FollowCameraMouseWheelInput: function () {},
    FollowCameraPointersInput: function () {},
    FreeCameraKeyboardMoveInput: function () {},
    FreeCameraMouseInput: function () {},
    FreeCameraTouchInput: function () {},
    FreeCameraDeviceOrientationInput: function () {},
    FreeCameraGamepadInput: function () {},
    FreeCameraVirtualJoystickInput: function () {},
  },
  CameraInputsManager: function () {},
  Camera: function () {},
  TargetCamera: function () {},
  FreeCamera: function () {},
  FreeCameraInputsManager: function () {},
  TouchCamera: function () {},
  ArcRotateCamera: function () {},
  ArcRotateCameraInputsManager: function () {},
  DeviceOrientationCamera: function () {},
  FlyCamera: function () {},
  FlyCameraInputsManager: function () {},
  FollowCamera: function () {},
  ArcFollowCamera: function () {},
  FollowCameraInputsManager: function () {},
  GamepadCamera: function () {},
  UniversalCamera: function () {},
  VirtualJoysticksCamera: function () {},
  Collider: function () {},
  DefaultCollisionCoordinator: function () {},
  PickingInfo: function () {},
  IntersectionInfo: function () {},
  _MeshCollisionData: function () {},
  BoundingBox: function () {},
  BoundingInfo: function () {},
  BoundingSphere: function () {},
  Ray: function () {},
  AxesViewer: function () {},
  BoneAxesViewer: function () {},
  DebugLayerTab: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    Properties: {},
    Debug: {},
    Statistics: {},
    Tools: {},
    Settings: {},
  },
  DebugLayer: function () {},
  PhysicsViewer: function () {},
  RayHelper: function () {},
  SkeletonViewer: function () {},
  Constants: function () {},
  ThinEngine: function () {},
  Engine: function () {},
  EngineStore: function () {},
  NullEngineOptions: function () {},
  NullEngine: function () {},
  WebGLPipelineContext: function () {},
  WebGL2ShaderProcessor: function () {},
  NativeEngine: function () {},
  KeyboardEventTypes: function () {},
  KeyboardInfo: function () {},
  KeyboardInfoPre: function () {},
  PointerEventTypes: function () {},
  PointerInfoBase: function () {},
  PointerInfoPre: function () {},
  PointerInfo: function () {},
  ClipboardEventTypes: function () {},
  ClipboardInfo: function () {},
  StickValues: function () {},
  Gamepad: function () {},
  GenericPad: function () {},
  GamepadManager: function () {},
  GamepadSystemSceneComponent: function () {},
  Xbox360Button: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    "8": {},
    "9": {},
    "10": {},
    "11": {},
    A: {},
    B: {},
    X: {},
    Y: {},
    LB: {},
    RB: {},
    Back: {},
    Start: {},
    LeftStick: {},
    RightStick: {},
  },
  Xbox360Dpad: {
    "12": {},
    "13": {},
    "14": {},
    "15": {},
    Up: {},
    Down: {},
    Left: {},
    Right: {},
  },
  Xbox360Pad: function () {},
  DualShockButton: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    "8": {},
    "9": {},
    "10": {},
    "11": {},
    Cross: {},
    Circle: {},
    Square: {},
    Triangle: {},
    L1: {},
    R1: {},
    Share: {},
    Options: {},
    LeftStick: {},
    RightStick: {},
  },
  DualShockDpad: {
    "12": {},
    "13": {},
    "14": {},
    "15": {},
    Up: {},
    Down: {},
    Left: {},
    Right: {},
  },
  DualShockPad: function () {},
  AxisDragGizmo: function () {},
  AxisScaleGizmo: function () {},
  BoundingBoxGizmo: function () {},
  Gizmo: function () {},
  GizmoManager: function () {},
  PlaneRotationGizmo: function () {},
  PositionGizmo: function () {},
  RotationGizmo: function () {},
  ScaleGizmo: function () {},
  LightGizmo: function () {},
  PlaneDragGizmo: function () {},
  EnvironmentHelper: function () {},
  PhotoDome: function () {},
  _forceSceneHelpersToBundle: {},
  VideoDome: function () {},
  EngineInstrumentation: function () {},
  SceneInstrumentation: function () {},
  _TimeToken: function () {},
  EffectLayer: function () {},
  EffectLayerSceneComponent: function () {},
  GlowLayer: function () {},
  HighlightLayer: function () {},
  Layer: function () {},
  LayerSceneComponent: function () {},
  LensFlare: function () {},
  LensFlareSystem: function () {},
  LensFlareSystemSceneComponent: function () {},
  Light: function () {},
  ShadowLight: function () {},
  DirectionalLight: function () {},
  HemisphericLight: function () {},
  PointLight: function () {},
  SpotLight: function () {},
  DefaultLoadingScreen: function () {},
  SceneLoaderProgressEvent: function () {},
  SceneLoaderAnimationGroupLoadingMode: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    Clean: {},
    Stop: {},
    Sync: {},
    NoSync: {},
  },
  SceneLoader: function () {},
  SceneLoaderFlags: function () {},
  ColorCurves: function () {},
  EffectFallbacks: function () {},
  Effect: function () {},
  FresnelParameters: function () {},
  ImageProcessingConfigurationDefines: function () {},
  ImageProcessingConfiguration: function () {},
  Material: function () {},
  MaterialDefines: function () {},
  MaterialHelper: function () {},
  MultiMaterial: function () {},
  PBRMaterial: function () {},
  PushMaterial: function () {},
  ShaderMaterial: function () {},
  StandardMaterialDefines: function () {},
  StandardMaterial: function () {},
  BaseTexture: function () {},
  CubeTexture: function () {},
  DynamicTexture: function () {},
  EquiRectangularCubeTexture: function () {},
  HDRCubeTexture: function () {},
  InternalTextureSource: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    "6": {},
    "7": {},
    "8": {},
    "9": {},
    "10": {},
    "11": {},
    "12": {},
    "13": {},
    Unknown: {},
    Url: {},
    Temp: {},
    Raw: {},
    Dynamic: {},
    RenderTarget: {},
    MultiRenderTarget: {},
    Cube: {},
    CubeRaw: {},
    CubePrefiltered: {},
    Raw3D: {},
    Raw2DArray: {},
    Depth: {},
    CubeRawRGBD: {},
  },
  InternalTexture: function () {},
  MirrorTexture: function () {},
  MultiRenderTarget: function () {},
  RawTexture: function () {},
  RenderTargetTexture: function () {},
  Texture: function () {},
  UniformBuffer: function () {},
  MaterialFlags: function () {},
  EffectRenderer: function () {},
  EffectWrapper: function () {},
  Scalar: function () {},
  Space: {
    "0": {},
    "1": {},
    "2": {},
    LOCAL: {},
    WORLD: {},
    BONE: {},
  },
  Axis: function () {},
  Color3: function () {},
  Color4: function () {},
  TmpColors: function () {},
  ToGammaSpace: {},
  ToLinearSpace: {},
  Epsilon: {},
  Frustum: function () {},
  Plane: function () {},
  Size: function () {},
  Vector2: function () {},
  Vector3: function () {},
  Vector4: function () {},
  Quaternion: function () {},
  Matrix: function () {},
  TmpVectors: function () {},
  Viewport: function () {},
  SphericalHarmonics: function () {},
  SphericalPolynomial: function () {},
  AbstractMesh: function () {},
  Buffer: function () {},
  VertexBuffer: function () {},
  CSG: function () {},
  Geometry: function () {},
  GroundMesh: function () {},
  TrailMesh: function () {},
  InstancedMesh: function () {},
  LinesMesh: function () {},
  InstancedLinesMesh: function () {},
  _CreationDataStorage: function () {},
  _InstancesBatch: function () {},
  Mesh: function () {},
  VertexData: function () {},
  MeshBuilder: function () {},
  SimplificationSettings: function () {},
  SimplificationQueue: function () {},
  SimplificationType: {
    "0": {},
    QUADRATIC: {},
  },
  SimplicationQueueSceneComponent: function () {},
  Polygon: function () {},
  PolygonMeshBuilder: function () {},
  BaseSubMesh: function () {},
  SubMesh: function () {},
  MeshLODLevel: function () {},
  TransformNode: function () {},
  BoxBuilder: function () {},
  SphereBuilder: function () {},
  CylinderBuilder: function () {},
  TorusBuilder: function () {},
  LinesBuilder: function () {},
  PlaneBuilder: function () {},
  GroundBuilder: function () {},
  DataBuffer: function () {},
  WebGLDataBuffer: function () {},
  MorphTarget: function () {},
  MorphTargetManager: function () {},
  Database: function () {},
  BaseParticleSystem: function () {},
  GPUParticleSystem: function () {},
  Particle: function () {},
  ParticleHelper: function () {},
  ParticleSystem: function () {},
  _IDoNeedToBeInTheBuild: {},
  ParticleSystemSet: function () {},
  SolidParticle: function () {},
  ModelShape: function () {},
  DepthSortedParticle: function () {},
  SolidParticleSystem: function () {},
  CloudPoint: function () {},
  PointsGroup: function () {},
  PointColor: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    Color: {},
    UV: {},
    Random: {},
    Stated: {},
  },
  PointsCloudSystem: function () {},
  SubEmitterType: {
    "0": {},
    "1": {},
    ATTACHED: {},
    END: {},
  },
  SubEmitter: function () {},
  PhysicsEngine: function () {},
  PhysicsEngineSceneComponent: function () {},
  PhysicsHelper: function () {},
  PhysicsRadialExplosionEventOptions: function () {},
  PhysicsUpdraftEventOptions: function () {},
  PhysicsVortexEventOptions: function () {},
  PhysicsRadialImpulseFalloff: {
    "0": {},
    "1": {},
    Constant: {},
    Linear: {},
  },
  PhysicsUpdraftMode: {
    "0": {},
    "1": {},
    Center: {},
    Perpendicular: {},
  },
  PhysicsImpostor: function () {},
  PhysicsJoint: function () {},
  DistanceJoint: function () {},
  MotorEnabledJoint: function () {},
  HingeJoint: function () {},
  Hinge2Joint: function () {},
  AnaglyphPostProcess: function () {},
  BlackAndWhitePostProcess: function () {},
  BloomEffect: function () {},
  BloomMergePostProcess: function () {},
  BlurPostProcess: function () {},
  ChromaticAberrationPostProcess: function () {},
  CircleOfConfusionPostProcess: function () {},
  ColorCorrectionPostProcess: function () {},
  ConvolutionPostProcess: function () {},
  DepthOfFieldBlurPostProcess: function () {},
  DepthOfFieldEffectBlurLevel: {
    "0": {},
    "1": {},
    "2": {},
    Low: {},
    Medium: {},
    High: {},
  },
  DepthOfFieldEffect: function () {},
  DepthOfFieldMergePostProcessOptions: function () {},
  DepthOfFieldMergePostProcess: function () {},
  DisplayPassPostProcess: function () {},
  ExtractHighlightsPostProcess: function () {},
  FilterPostProcess: function () {},
  FxaaPostProcess: function () {},
  GrainPostProcess: function () {},
  HighlightsPostProcess: function () {},
  ImageProcessingPostProcess: function () {},
  MotionBlurPostProcess: function () {},
  PassPostProcess: function () {},
  PassCubePostProcess: function () {},
  PostProcess: function () {},
  PostProcessManager: function () {},
  RefractionPostProcess: function () {},
  SharpenPostProcess: function () {},
  StereoscopicInterlacePostProcessI: function () {},
  StereoscopicInterlacePostProcess: function () {},
  TonemappingOperator: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    Hable: {},
    Reinhard: {},
    HejiDawson: {},
    Photographic: {},
  },
  TonemapPostProcess: function () {},
  VolumetricLightScatteringPostProcess: function () {},
  VRDistortionCorrectionPostProcess: function () {},
  VRMultiviewToSingleviewPostProcess: function () {},
  ScreenSpaceReflectionPostProcess: function () {},
  ReflectionProbe: function () {},
  BoundingBoxRenderer: function () {},
  DepthRenderer: function () {},
  DepthRendererSceneComponent: function () {},
  EdgesRenderer: function () {},
  LineEdgesRenderer: function () {},
  GeometryBufferRenderer: function () {},
  GeometryBufferRendererSceneComponent: function () {},
  OutlineRenderer: function () {},
  RenderingGroup: function () {},
  RenderingGroupInfo: function () {},
  RenderingManager: function () {},
  UtilityLayerRenderer: function () {},
  Sprite: function () {},
  SpriteManager: function () {},
  SpriteMap: function () {},
  SpritePackedManager: function () {},
  SpriteSceneComponent: function () {},
  AlphaState: function () {},
  DepthCullingState: function () {},
  StencilState: function () {},
  AndOrNotEvaluator: function () {},
  AssetTaskState: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    INIT: {},
    RUNNING: {},
    DONE: {},
    ERROR: {},
  },
  AbstractAssetTask: function () {},
  AssetsProgressEvent: function () {},
  MeshAssetTask: function () {},
  TextFileAssetTask: function () {},
  BinaryFileAssetTask: function () {},
  ImageAssetTask: function () {},
  TextureAssetTask: function () {},
  CubeTextureAssetTask: function () {},
  HDRCubeTextureAssetTask: function () {},
  EquiRectangularCubeTextureAssetTask: function () {},
  AssetsManager: function () {},
  BasisTranscodeConfiguration: function () {},
  BasisTools: function () {},
  DDSTools: function () {},
  expandToProperty: function () {},
  serialize: function () {},
  serializeAsTexture: function () {},
  serializeAsColor3: function () {},
  serializeAsFresnelParameters: function () {},
  serializeAsVector2: function () {},
  serializeAsVector3: function () {},
  serializeAsMeshReference: function () {},
  serializeAsColorCurves: function () {},
  serializeAsColor4: function () {},
  serializeAsImageProcessingConfiguration: function () {},
  serializeAsQuaternion: function () {},
  serializeAsMatrix: function () {},
  serializeAsCameraReference: function () {},
  SerializationHelper: function () {},
  Deferred: function () {},
  EnvironmentTextureTools: function () {},
  MeshExploder: function () {},
  FilesInput: function () {},
  KhronosTextureContainer: function () {},
  EventState: function () {},
  Observer: function () {},
  MultiObserver: function () {},
  Observable: function () {},
  PerformanceMonitor: function () {},
  RollingAverage: function () {},
  PromisePolyfill: function () {},
  SceneOptimization: function () {},
  TextureOptimization: function () {},
  HardwareScalingOptimization: function () {},
  ShadowsOptimization: function () {},
  PostProcessesOptimization: function () {},
  LensFlaresOptimization: function () {},
  CustomOptimization: function () {},
  ParticlesOptimization: function () {},
  RenderTargetsOptimization: function () {},
  MergeMeshesOptimization: function () {},
  SceneOptimizerOptions: function () {},
  SceneOptimizer: function () {},
  SceneSerializer: function () {},
  SmartArray: function () {},
  SmartArrayNoDuplicate: function () {},
  StringDictionary: function () {},
  Tags: function () {},
  TextureTools: function () {},
  TGATools: function () {},
  Tools: function () {},
  className: function () {},
  AsyncLoop: function () {},
  VideoRecorder: function () {},
  JoystickAxis: {
    "0": {},
    "1": {},
    "2": {},
    X: {},
    Y: {},
    Z: {},
  },
  VirtualJoystick: function () {},
  WorkerPool: function () {},
  Logger: function () {},
  _TypeStore: function () {},
  FilesInputStore: function () {},
  DeepCopier: function () {},
  PivotTools: function () {},
  PrecisionDate: function () {},
  ScreenshotTools: function () {},
  WebRequest: function () {},
  InspectableType: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    Checkbox: {},
    Slider: {},
    Vector3: {},
    Quaternion: {},
    Color3: {},
    String: {},
  },
  BRDFTextureTools: function () {},
  RGBDTextureTools: function () {},
  ColorGradient: function () {},
  Color3Gradient: function () {},
  FactorGradient: function () {},
  GradientHelper: function () {},
  PerfCounter: function () {},
  RetryStrategy: function () {},
  CanvasGenerator: function () {},
  LoadFileError: function () {},
  RequestFileError: function () {},
  ReadFileError: function () {},
  FileTools: function () {},
  StringTools: function () {},
  DataReader: function () {},
  MinMaxReducer: function () {},
  DepthReducer: function () {},
  WebXRCamera: function () {},
  WebXREnterExitUIButton: function () {},
  WebXREnterExitUIOptions: function () {},
  WebXREnterExitUI: function () {},
  WebXRExperienceHelper: function () {},
  WebXRInput: function () {},
  WebXRInputSource: function () {},
  WebXRManagedOutputCanvasOptions: function () {},
  WebXRManagedOutputCanvas: function () {},
  WebXRState: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    ENTERING_XR: {},
    EXITING_XR: {},
    IN_XR: {},
    NOT_IN_XR: {},
  },
  WebXRSessionManager: function () {},
  WebXRDefaultExperienceOptions: function () {},
  WebXRDefaultExperience: function () {},
  WebXRFeatureName: function () {},
  WebXRFeaturesManager: function () {},
  AutoRotationBehavior: function () {},
  BouncingBehavior: function () {},
  FramingBehavior: function () {},
  AttachToBoxBehavior: function () {},
  FadeInOutBehavior: function () {},
  MultiPointerScaleBehavior: function () {},
  PointerDragBehavior: function () {},
  SixDofDragBehavior: function () {},
  ArcRotateCameraGamepadInput: function () {},
  ArcRotateCameraKeyboardMoveInput: function () {},
  ArcRotateCameraMouseWheelInput: function () {},
  ArcRotateCameraPointersInput: function () {},
  ArcRotateCameraVRDeviceOrientationInput: function () {},
  FlyCameraKeyboardInput: function () {},
  FlyCameraMouseInput: function () {},
  FollowCameraKeyboardMoveInput: function () {},
  FollowCameraMouseWheelInput: function () {},
  FollowCameraPointersInput: function () {},
  FreeCameraDeviceOrientationInput: function () {},
  FreeCameraGamepadInput: function () {},
  FreeCameraKeyboardMoveInput: function () {},
  FreeCameraMouseInput: function () {},
  FreeCameraTouchInput: function () {},
  FreeCameraVirtualJoystickInput: function () {},
  AnaglyphArcRotateCamera: function () {},
  AnaglyphFreeCamera: function () {},
  AnaglyphGamepadCamera: function () {},
  AnaglyphUniversalCamera: function () {},
  StereoscopicArcRotateCamera: function () {},
  StereoscopicFreeCamera: function () {},
  StereoscopicGamepadCamera: function () {},
  StereoscopicUniversalCamera: function () {},
  VRCameraMetrics: function () {},
  VRDeviceOrientationArcRotateCamera: function () {},
  VRDeviceOrientationFreeCamera: function () {},
  VRDeviceOrientationGamepadCamera: function () {},
  OnAfterEnteringVRObservableEvent: function () {},
  VRExperienceHelper: function () {},
  WebVRFreeCamera: function () {},
  Octree: function () {},
  OctreeBlock: function () {},
  OctreeSceneComponent: function () {},
  _OcclusionDataStorage: function () {},
  _forceTransformFeedbackToBundle: {},
  EngineView: function () {},
  DaydreamController: function () {},
  GearVRController: function () {},
  GenericController: function () {},
  OculusTouchController: function () {},
  PoseEnabledControllerType: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    VIVE: {},
    OCULUS: {},
    WINDOWS: {},
    GEAR_VR: {},
    DAYDREAM: {},
    GENERIC: {},
  },
  PoseEnabledControllerHelper: function () {},
  PoseEnabledController: function () {},
  ViveController: function () {},
  WebVRController: function () {},
  WindowsMotionController: function () {},
  XRWindowsMotionController: function () {},
  ShadowGenerator: function () {},
  CascadedShadowGenerator: function () {},
  ShadowGeneratorSceneComponent: function () {},
  _BabylonLoaderRegistered: {},
  BabylonFileLoaderConfiguration: function () {},
  BackgroundMaterial: function () {},
  PBRMaterialDefines: function () {},
  PBRBaseMaterial: function () {},
  PBRBaseSimpleMaterial: function () {},
  PBRMetallicRoughnessMaterial: function () {},
  PBRSpecularGlossinessMaterial: function () {},
  ColorGradingTexture: function () {},
  RawCubeTexture: function () {},
  RawTexture3D: function () {},
  RawTexture2DArray: function () {},
  RefractionTexture: function () {},
  VideoTexture: function () {},
  HtmlElementTexture: function () {},
  NodeMaterialConnectionPointCompatibilityStates: {
    "0": {},
    "1": {},
    "2": {},
    Compatible: {},
    TypeIncompatible: {},
    TargetIncompatible: {},
  },
  NodeMaterialConnectionPointDirection: {
    "0": {},
    "1": {},
    Input: {},
    Output: {},
  },
  NodeMaterialConnectionPoint: function () {},
  NodeMaterialBlock: function () {},
  NodeMaterialDefines: function () {},
  NodeMaterial: function () {},
  Orientation: {
    "0": {},
    "1": {},
    CW: {},
    CCW: {},
  },
  BezierCurve: function () {},
  Angle: function () {},
  Arc2: function () {},
  Path2: function () {},
  Path3D: function () {},
  Curve3: function () {},
  PositionNormalVertex: function () {},
  PositionNormalTextureVertex: function () {},
  DracoCompression: function () {},
  TiledBoxBuilder: function () {},
  DiscBuilder: function () {},
  RibbonBuilder: function () {},
  HemisphereBuilder: function () {},
  TorusKnotBuilder: function () {},
  PolygonBuilder: function () {},
  ShapeBuilder: function () {},
  LatheBuilder: function () {},
  TiledPlaneBuilder: function () {},
  TubeBuilder: function () {},
  PolyhedronBuilder: function () {},
  IcoSphereBuilder: function () {},
  DecalBuilder: function () {},
  RecastJSPlugin: function () {},
  RecastJSCrowd: function () {},
  BoxParticleEmitter: function () {},
  ConeParticleEmitter: function () {},
  CylinderParticleEmitter: function () {},
  CylinderDirectedParticleEmitter: function () {},
  HemisphericParticleEmitter: function () {},
  PointParticleEmitter: function () {},
  SphereParticleEmitter: function () {},
  SphereDirectedParticleEmitter: function () {},
  CustomParticleEmitter: function () {},
  MeshParticleEmitter: function () {},
  CannonJSPlugin: function () {},
  AmmoJSPlugin: function () {},
  OimoJSPlugin: function () {},
  PostProcessRenderEffect: function () {},
  PostProcessRenderPipeline: function () {},
  PostProcessRenderPipelineManager: function () {},
  PostProcessRenderPipelineManagerSceneComponent: function () {},
  CubeMapToSphericalPolynomialTools: function () {},
  HDRTools: function () {},
  PanoramaToCubeMapTools: function () {},
  WebXRHitTestLegacy: function () {},
  WebXRAnchorSystem: function () {},
  WebXRPlaneDetector: function () {},
  WebXRBackgroundRemover: function () {},
  WebXRMotionControllerTeleportation: function () {},
  WebXRControllerPointerSelection: function () {},
  IWebXRControllerPhysicsOptions: function () {},
  WebXRControllerPhysics: function () {},
  WebXRAbstractMotionController: function () {},
  WebXRControllerComponent: function () {},
  WebXRGenericTriggerMotionController: function () {},
  WebXRMicrosoftMixedRealityController: function () {},
  WebXRMotionControllerManager: function () {},
  WebXROculusTouchMotionController: function () {},
  WebXRHTCViveMotionController: function () {},
  WebXRProfiledMotionController: function () {},
  _DDSTextureLoader: function () {},
  _ENVTextureLoader: function () {},
  _KTXTextureLoader: function () {},
  _TGATextureLoader: function () {},
  _BasisTextureLoader: function () {},
  CustomProceduralTexture: function () {},
  NoiseProceduralTexture: function () {},
  ProceduralTexture: function () {},
  ProceduralTextureSceneComponent: function () {},
  TexturePacker: function () {},
  TexturePackerFrame: function () {},
  NodeMaterialBlockTargets: {
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    Vertex: {},
    Fragment: {},
    Neutral: {},
    VertexAndFragment: {},
  },
  NodeMaterialBlockConnectionPointTypes: {
    "1": {},
    "2": {},
    "4": {},
    "8": {},
    "16": {},
    "32": {},
    "64": {},
    "128": {},
    "1024": {},
    "2048": {},
    Float: {},
    Int: {},
    Vector2: {},
    Vector3: {},
    Vector4: {},
    Color3: {},
    Color4: {},
    Matrix: {},
    AutoDetect: {},
    BasedOnInput: {},
  },
  NodeMaterialBlockConnectionPointMode: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    Uniform: {},
    Attribute: {},
    Varying: {},
    Undefined: {},
  },
  NodeMaterialSystemValues: {
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    "6": {},
    "7": {},
    "8": {},
    "9": {},
    World: {},
    View: {},
    Projection: {},
    ViewProjection: {},
    WorldView: {},
    WorldViewProjection: {},
    CameraPosition: {},
    FogColor: {},
    DeltaTime: {},
  },
  MultiplyBlock: function () {},
  AddBlock: function () {},
  ScaleBlock: function () {},
  ClampBlock: function () {},
  CrossBlock: function () {},
  DotBlock: function () {},
  TransformBlock: function () {},
  RemapBlock: function () {},
  NormalizeBlock: function () {},
  TrigonometryBlockOperations: {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
    "4": {},
    "5": {},
    "6": {},
    "7": {},
    "8": {},
    "9": {},
    "10": {},
    "11": {},
    "12": {},
    "13": {},
    "14": {},
    "15": {},
    "16": {},
    "17": {},
    Cos: {},
    Sin: {},
    Abs: {},
    Exp: {},
    Exp2: {},
    Round: {},
    Floor: {},
    Ceiling: {},
    Sqrt: {},
    Log: {},
    Tan: {},
    ArcTan: {},
    ArcCos: {},
    ArcSin: {},
    Fract: {},
    Sign: {},
    Radians: {},
    Degrees: {},
  },
  TrigonometryBlock: function () {},
  ColorMergerBlock: function () {},
  VectorMergerBlock: function () {},
  ColorSplitterBlock: function () {},
  VectorSplitterBlock: function () {},
  LerpBlock: function () {},
  DivideBlock: function () {},
  SubtractBlock: function () {},
  StepBlock: function () {},
  OneMinusBlock: function () {},
  ViewDirectionBlock: function () {},
  FresnelBlock: function () {},
  MaxBlock: function () {},
  MinBlock: function () {},
  DistanceBlock: function () {},
  LengthBlock: function () {},
  NegateBlock: function () {},
  PowBlock: function () {},
  RandomNumberBlock: function () {},
  ArcTan2Block: function () {},
  SmoothStepBlock: function () {},
  ReciprocalBlock: function () {},
  ReplaceColorBlock: function () {},
  PosterizeBlock: function () {},
  WaveBlockKind: {
    "0": {},
    "1": {},
    "2": {},
    SawTooth: {},
    Square: {},
    Triangle: {},
  },
  WaveBlock: function () {},
  GradientBlockColorStep: function () {},
  GradientBlock: function () {},
  NLerpBlock: function () {},
  WorleyNoise3DBlock: function () {},
  SimplexPerlin3DBlock: function () {},
  NormalBlendBlock: function () {},
  Rotate2dBlock: function () {},
  ReflectBlock: function () {},
  RefractBlock: function () {},
  DesaturateBlock: function () {},
  NodeMaterialOptimizer: function () {},
  DefaultRenderingPipeline: function () {},
  LensRenderingPipeline: function () {},
  SSAO2RenderingPipeline: function () {},
  SSAORenderingPipeline: function () {},
  StandardRenderingPipeline: function () {},
  VertexOutputBlock: function () {},
  BonesBlock: function () {},
  InstancesBlock: function () {},
  MorphTargetsBlock: function () {},
  LightInformationBlock: function () {},
  FragmentOutputBlock: function () {},
  ImageProcessingBlock: function () {},
  PerturbNormalBlock: function () {},
  DiscardBlock: function () {},
  FrontFacingBlock: function () {},
  DerivativeBlock: function () {},
  FogBlock: function () {},
  LightBlock: function () {},
  TextureBlock: function () {},
  ReflectionTextureBlock: function () {},
  InputBlock: function () {},
  AnimatedInputBlockTypes: {
    "0": {},
    "1": {},
    None: {},
    Time: {},
  },
};
